---
name: Framework Wallpapers
on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Release for Framework Wallpapers with Gnome and KDE support
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # We need a newish version of kimageformats, 24.04 doesn't have it
    container: docker.io/library/ubuntu:25.04@sha256:103c7471649a4fd9996fe73dff20f46082e4e0f0f6240c91954b8b09c38b6faf

    steps:

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Create tarballs
        shell: bash
        run: |
          # Create separate archives for each platform
          mkdir -p output/packaging/macos
          mkdir -p output/packaging/kde
          mkdir -p output/packaging/gnome/images
          mkdir -p output/packaging/png
          
          # macOS: HEIC dynamic wallpapers
          cp wallpapers/framework/macos/*.heic output/packaging/macos/
          cd output/packaging/macos && tar -acvf ../framework-wallpapers-macos.tar.zstd *.heic && cd -
          
          # KDE: AVIF wallpapers
          cp wallpapers/framework/kde/*.avif output/packaging/kde/
          cd output/packaging/kde && tar -acvf ../framework-wallpapers-kde.tar.zstd *.avif && cd -
          
          # GNOME: SVG wallpapers + XML metadata
          cp wallpapers/framework/*.svg output/packaging/gnome/images/
          cp wallpapers/framework/gnome/*.xml output/packaging/gnome/images/
          cp -R wallpapers/framework/gnome/gnome-background-properties output/packaging/gnome/
          cd output/packaging/gnome && tar -acvf ../framework-wallpapers-gnome.tar.zstd * && cd -
          
          # PNG: For other desktops
          cp wallpapers/framework/png/*.png output/packaging/png/
          cd output/packaging/png && tar -acvf ../framework-wallpapers-png.tar.zstd *.png && cd -

      - name: Determine tag
        id: tag
        run: echo "tag=v$(date --iso-8601=date)" >> "$GITHUB_OUTPUT"

      - name: Publish release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
        with:
          tag:   ${{ steps.tag.outputs.tag }}
          allowUpdates: true
          name:  "${{ steps.tag.outputs.tag }}"
          artifacts: "output/packaging/framework-wallpapers-*.tar.zstd"
          token: ${{ secrets.GITHUB_TOKEN }}
